OnCode/OnCode/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('onCode.urls'))
]

OnCode/onCode/urls.py
from django.conf.urls import url
from onCode import views

urlpatterns = [
    url(r'^leaderboard/$', views.LeaderboardView.as_view(), name='leaderboard_view'),
    url(r'^Problem/(?P<pk>[0-9]+)/$',
        views.ProblemDetailView.as_view(),
        name='problem_detail'),
    url(r'^Problem/(?P<pk>[0-9]+)/ViewComments/$',
        views.ViewComments.as_view(),
        name="view_comment"),
    url(r'^Problem/(?P<pk>[0-9]+)/AddComment/$',
        views.AddComment.as_view(),
        name="add_comment"
        ),
    url(r'^$', views.ProblemsListView.as_view(), name='problem_list_view'),
    url(r'^create-user/$', views.UserCreateView.as_view(), name='user-create-view'),
    url(r'^userprofile/(?P<pk>[0-9]+)/$', views.UserProfileDetailView.as_view(), name='user-profile-view'),
    url(r'^userprofile/(?P<pk>[0-9]+)/edit/$', views.UserUpdateView.as_view(), name='user-edit-profile-view'),
    url(r'^login', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^Problem/(?P<pk>[0-9]+)/Input/$',
        views.GetInput.as_view(),
        name="get_input"
        ),
    url(r'^Problem/(?P<pk>[0-9]+)/SubmitSolution/$',
        views.SubmitSolution.as_view(),
        name="submit_solution"
        )

]

OnCode/onCode/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

difficulties = [('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'God')]


# Create your models here.

class UserProfile(models.Model):
    user_pk = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True)
    university = models.CharField(max_length=100, null=True)
    score = models.IntegerField(null=True)

    def __str__(self):
        return self.user_pk.first_name + ' ' + self.user_pk.last_name


class Problem(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=350)
    difficulty = models.CharField(max_length=50, choices=difficulties)
    hints = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Rezolvari(models.Model):
    test = models.CharField(max_length=150000)
    answer = models.CharField(max_length=150000)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)


class Comment(models.Model):
    problem_id = models.ForeignKey(Problem, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text
        
class ResolvedProblems(models.Model):
    problem_id = models.ForeignKey(Problem, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = ('problem_id', 'user_id')

    def __str__(self):
        return self.problem_id.title + " " + self.user_id.username

OnCode/onCode/forms.py
from django import forms
from django.contrib.auth.models import User
from  models import *


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username', 'first_name', 'last_name', 'password'
        )

    password = forms.CharField(widget=forms.PasswordInput())
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class UserEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'birth_date', 'university')

    birth_date = forms.DateField(required=True)
    university = forms.CharField(required=True)


class SubmitSolutionForm(forms.ModelForm):
    class Meta:
        model = Rezolvari
        fields = ('answer',)

    answer = forms.Textarea()

OnCode/onCode/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from models import *
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from forms import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class LeaderboardView(ListView):
    # import pdb;pdb.set_trace()
    model = UserProfile
    template_name = 'leaderboard-view.html'
    context_object_name = 'users'
    ordering = ['-score']


class ProblemDetailView(DetailView):
    template_name = 'problem.html'
    model = Problem
    context_object_name = 'problem'
    
    def get_context_data(self, **kwargs):
        context = super(ProblemDetailView, self).get_context_data(**kwargs)
        context['data'] = {
            'is_logged_user' : self.request.user.is_authenticated,
            'is_problem_resolved' : ResolvedProblems.objects.filter(problem_id = Problem.objects.get(pk = self.kwargs.get('pk')))
                        .filter(user_id = User.objects.get(pk = self.request.user.pk)).exists() 
        }
        
        return context
        


class ViewComments(ListView):
    template_name = 'viewComment.html'
    model = Comment
    context_object_name = 'Comment'

    def get_queryset(self, *args, **kwargs):
        return Comment.objects.filter(problem_id=self.kwargs.get('pk'))


class UserProfileDetailView(DetailView):
    template_name = 'user-profile-details.html'
    model = UserProfile
    context_object_name = 'userprofile'
    
    def get_context_data(self, **kwargs):

        context = super(UserProfileDetailView, self).get_context_data(**kwargs)
        context['data'] = {
            'resolved_problems':ResolvedProblems.objects.filter(user_id = self.kwargs['pk']),
            'is_logged_user':self.request.user.is_authenticated
        }
        
        return context


class ProblemsListView(ListView):
    model = Problem
    template_name = 'problems-view-list.html'
    context_object_name = 'problems'


class UserCreateView(CreateView):
    form_class = UserCreateForm
    template_name = 'user-create-view.html'
    model = User

    def get_success_url(self, *args, **kwargs):
        profile = UserProfile(user_pk=self.object, score=0)
        profile.save()
        return reverse(
            'user-edit-profile-view',
            kwargs={
                'pk': self.object.pk
            }
        )


class AddComment(LoginRequiredMixin, CreateView):
    template_name = 'addComment.html'
    model = Comment
    form_class = AddCommentForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_id = User.objects.get(pk=self.request.user.id)
        self.object.problem_id = Problem.objects.get(pk=self.kwargs.get('pk'))
        self.object.save()
        return super(AddComment, self).form_valid(form)

    def get_success_url(self):
        return reverse(
            'view_comment',
            kwargs={
                'pk': self.kwargs.get('pk')
            }
        )


def login_view(request):
    context = {}
    if request.method == 'GET':
        form = LoginForm()
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user:
                login(request=request,
                      user=user)
                return redirect('problem_list_view')
            else:
                context['error_message'] = 'Wrong username or password!'
    context['form'] = form
    return render(request, 'login.html', context)


def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return redirect('login')


class UserUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'user-edit-profile-view.html'
    form_class = UserEditForm
    model = UserProfile

    def get_success_url(self, *args, **kwargs):
        return reverse(
            'user-profile-view',
            kwargs={
                'pk': self.kwargs['pk']
            }
        )


class GetInput(DetailView):
    model = Rezolvari
    template_name = "getInput.html"
    context_object_name = "rezolvari"
    #

    # def get_context_data(self, **kwargs):
    #     context = super(GetInput, self).get_context_data(**kwargs)
    #     context['x'] =  Rezolvari.objects.filter(problem=self.kwargs.get('pk'))
    # def get_queryset(self, *args, **kwargs):
    #     return Rezolvari.objects.filter(problem=self.kwargs.get('pk'))


class SubmitSolution(LoginRequiredMixin, UpdateView):
    model = User
    template_name = "submitSolution.html"
    context_object_name = "user"
    form_class = SubmitSolutionForm

    def form_valid(self, form):
        # import pdb;pdb.set_trace()
        user_id = self.request.user.id
        self.object = form.save(commit=False)
        raspuns = form.cleaned_data['answer']
        answer = Rezolvari.objects.get(problem=self.kwargs.get('pk')).answer
        pk = self.kwargs.get('pk')
        user = UserProfile.objects.get(pk=user_id)
        score = user.score
        problem = Problem.objects.get(pk=self.kwargs.get('pk'))
        difficultate = problem.difficulty
        difficulties = {'1': 25, '2': 50, '3': 75, '4': 100}
        if answer == raspuns:
            problrez = ResolvedProblems(user_id=User.objects.get(pk=user_id), problem_id=problem)
            problrez.save()
            score += difficulties[str(difficultate)]
        user.score = score
        user.save()
        return super(SubmitSolution, self).form_valid(form)


    def get_success_url(self):
        return reverse('problem_detail', kwargs={'pk': self.kwargs.get('pk')})

OnCode/onCode/templates/addComment.html
{% extends 'layout.html' %} {% block title %}Add comment{% endblock %} {% block content %}

<div class='container edit-task'>

    <p class='title'>Add Comment</p>
    <form method="POST" enctype="multipart/formdata" class="form">
        {% csrf_token %} {{ form.as_p }}
        <div class='group'>
            <button class='btn btn-success left' type="submit">Save</button>
        </div>
    </form>
</div>

{% endblock %}

OnCode/onCode/templates/getInput.html
{% extends 'layout.html' %}

{% block title %}{% endblock %}

{% block content %}
{{ rezolvari.test }}


{% endblock %}

OnCode/onCode/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>{% block title %}{% endblock %}</title>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>

    <body>
        <div id="divBarMenu">

            <div id="divAutentification">
                <a href="/userprofile/{{request.user.id}}">
        <button class="btn btn-primary">
            View Profile
        </button>
    </a>
    <a href="/leaderboard">
        <button class="btn btn-primary">
            Leaderboard
        </button>
    </a>
                 <a href="/">
        <button class="btn btn-primary">
            Problems
        </button>
    </a>
            </div>
        </div>
        
    <div class="container">

        {% block content %}{% endblock %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>

</html>

OnCode/onCode/templates/leaderboard-view.html
{% extends 'layout.html' %} {% block title %}Leaderboard{% endblock %} {% block content %}


<div>
    <p>Leaderboard</p>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <td>University</td>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.user_pk.first_name }}</td>
                <td>{{ user.university }}</td>
                <td>{{ user.score }}</td>
                <td>
                    <a href="/userprofile/{{ user.pk }}/">
                    User profile
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

OnCode/onCode/templates/login.html
{% extends 'layout.html' %} {% block title %}Login{% endblock %} {% block content %}

<h1>Login</h1>

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.errors }}
</div>
{% endif %}

<div id="divMenu">
    <div id="divEmpty">
    </div>
    <div id="divMenuReset">
        <div id="divResetTitle">
            <label id="resetTitle">Login</label>
        </div>
        <form method="POST" enctype="multipart/formdata" class="form">
            {% csrf_token %}
            <div class="form-group">
                <div class="divResetEmailLabel">
                    <label class="resetEmailLabel" for="id_username">Username:</label>
                </div>
                <div class="divResetEmailText">
                    <input class="resetEmailText" type="text" name="username" required="" id="id_username" class="form-control">
                </div>
                
            </div>
            <div class="form-group">
                <div class="divResetEmailLabel">
                    <label class="resetEmailLabel" for="id_password">Password:</label>
                </div>
                <div class="divResetEmailText">
                    <input class="resetEmailLabel" type="password" name="password" required="" id="id_password" class="form-control">
                </div>
                
                
            
                
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</div>


{% endblock %}

OnCode/onCode/templates/problem.html
{% extends 'layout.html' %} {% block title %}{{ problem.title }}{% endblock %} {% block content %}
<div id="divMenu">
    <div id="divEmpty">
    </div>
    <div id="divMenuReset">
        <div id="divResetTitle">
            <label id="resetTitle">{{problem.title}}</label>
        </div>
        <div class="divResetEmailLabel">
            <label class="resetEmailLabel"><b>Difficulty:</b></label>
        </div>
        <div class="divResetEmailText">
            <label class="resetEmailText"> {{problem.get_difficulty_display}}</label>
        </div>
        <div class="divResetEmailLabel">
            <label class="resetEmailLabel"><b>Hints:</b></label>
        </div>
        <div class="divResetEmailText">
            <label class="resetEmailText"> {{problem.hints}}</label>
        </div>

        <div>
            {{ problem.content }}
        </div>
        <div class="float-sm-left">
            <a href="/Problem/{{ problem.pk }}/Input" target="_blank">
            <button class="btn btn-primary">
                Get Problem Input
            </button>
        </a>
        </div>

        {% if data.is_logged_user and not data.is_problem_resolved %}
        <div class="float-sm-left">
            <a href="/Problem/{{ problem.pk }}/SubmitSolution" target="_blank">
            <button class="btn btn-primary">
                Submit
            </button>
        </a>

        </div>
        {% endif %} {% if data.is_logged_user %}
        <div class="float-sm-right">
            <a href="/Problem/{{ problem.pk }}/AddComment">

                <button class="btn btn-primary">
                    Add Comment
                </button>
            </a>
        </div>
        {% endif %}

        <div class="float-sm-right">
            <a href="/Problem/{{ problem.pk }}/ViewComments">
                <button class="btn btn-primary">
                   View comments
                </button></a>
        </div>

    </div>
</div>


{% endblock %}

OnCode/onCode/templates/problems-view-list.html
{% extends 'layout.html' %} {% block title %}Problems{% endblock %} {% block content %}

<div id="divMenu">
    <div id="divEmpty">
    </div>
    <div id="divMenuReset"> 
        <div id="divResetTitle">
            <label id="resetTitle">Probleme</label>
        </div>
        <table class='table'>
            <thead>
                <tr>
                    <th>Nr</th>
                    <th>Nume</th>
                    <th>Dificultate</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for problem in problems %}
                <tr>
                    <td>{{ problem.pk }}</td>
                    <td>{{ problem.title }}</td>
                    <td>{{ problem.get_difficulty_display }}</td>
                    <td>
                        <a href="/Problem/{{ problem.pk }}/">
                        <button class="btn btn-info">
                            Detalii
                        </button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    
    </div>
</div>    

{% endblock %}

OnCode/onCode/templates/submitSolution.html
{% extends 'layout.html' %} {% block title %}Enter solution{% endblock %} {% block content %}

<div class='container edit-task'>

    <form method="POST" enctype="multipart/formdata" class="form">
        {% csrf_token %} {{ form.as_p }}
        <div class='group'>
            <button class='btn btn-success left' type="submit">Save</button>
        </div>
    </form>
</div>

{% endblock %}

OnCode/onCode/templates/user-create-view.html
{% extends 'layout.html' %} {% block title %}Create usert{% endblock %} {% block content %}

<div class='container edit-task'>

    <p class='title'>Create user</p>
    <form method="POST" enctype="multipart/formdata" class="form">
        {% csrf_token %} {{ form.as_p }}
        <div class='group'>
            <button class='btn btn-success left' type="submit">Save</button>
        </div>
    </form>
</div>

{% endblock %}

OnCode/onCode/templates/user-edit-profile-view.html
{% extends 'layout.html' %} {% block title %}Edit profile{% endblock %} {% block content %}
<div class='container edit-user'>

    <p class='title'>Edit Profile</p>
    <form method="POST" enctype="multipart/formdata" class="form">
        {% csrf_token %} {{ form.as_p }}
        <div class='group'>
            <button class='btn btn-success left' type="submit">Save</button>
            </a>
        </div>
    </form>
</div>

{% endblock %}

OnCode/onCode/templates/user-profile-details.html
{% extends 'layout.html' %} {% block title %}User profile{% endblock %} {% block content %}

<div>
   
    <div class='container'>
    {% if data.is_logged_user %}
    <a href="/userprofile/{{ userprofile.user_pk.pk }}/edit">
                        Edit
    </a> {% endif %}
    <p><b>Username:</b> {{ userprofile.user_pk.username }}</p>

    <p><b>Name:</b>{{ userprofile.user_pk.first_name}} {{userprofile.user_pk.last_name }}</p>

    <p><b>Score:</b> {{ userprofile.score }}</p>

    <p><b>Birth date:</b> {{ userprofile.birth_date }}</p>

    <p><b>University:</b> {{ userprofile.university }}</p>
        <p class='title'>Lista probleme rezolvate</p>
        <table class='table'>
            <thead>
                <tr>
                    <th>Nr</th>
                    <th>Nume</th>
                    <th>Dificultate</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for problem in data.resolved_problems %}
                <tr>
                    <td>{{ problem.problem_id.pk }}</td>
                    <td>{{ problem.problem_id.title }}</td>
                    <td>{{ problem.problem_id.get_difficulty_display }}</td>
                    <td>
                        <a href="/Problem/{{ problem.pk }}/">
                        Details
                    </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

OnCode/onCode/templates/viewComment.html
{% extends 'layout.html' %} {% block title %}Comments{% endblock %} {% block content %}

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Comment</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for com in Comment %}
        <tr>
            <td>{{ com.user_id.username }}</td>
            <td>{{ com.text }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}